<?php

/**
 * Implements hook_preprocess().
 */
function sketch_preprocess(&$variables, $hook) {
  if ( !preg_match('/^pattern\_/', $hook)) {
    return;
  }
  foreach ($variables as $key => $values) {
    if (isset($variables[$key . '_override']) && !empty($variables[$key . '_override']) && !empty($variables[$key . '_override']['input'])) {
      $variables[$key] = $variables[$key . '_override'];
    }
  }
}